# - Topics for Analysis Paper

Choose the topic for your analysis paper among the following prompts^[You can slightly deviate from these questions, with my **previous** approval.]. Different teams can choose the same topic, but case studies need to be different.

- Does a colonial past shape the development path of a country? Use two case studies to develop your answer

- Is development a neo-colonial concept? Is it inherently racist? Compare and contrast different approaches to assess your answer.

- Choose a low-income country and detail the long-term influences of colonialism

-  Pick a side and develop your argument using a case study: Governance reforms are (not) necessary and (nor) feasible to promote economic development in Africa.

- Critically review how the concept of 'institutions' has been used in the development literature. How is it linked to development?

- Is good governance necessary for development? Use two case studies to develop your answer.

- Under what conditions does trade liberalization promote growth? Do a comparative analysis in which you contrast the case of two countries.

- Review the concept of the Washington Consensus. Contrast how it was applied in different countries (choose one Latin American and one African country) and the outcomes of the approach. Can we draw a causal claim about the effects of these policies on development?

- Does reliance on commodity exports lead to more volatile development? Review and contrast the experiences of two developing countries dependent on the export of different primary commodities.

- Is trade good for development? Choose a dimension and verify if, under this context, trade can boost development. You can do an in-depth country analysis or a cross-country comparison. 

- How do cities shape development? Do an in-depth analysis of urban clusters in Africa and find out more about the challenges that could prevent cities to become a tool for development.

- How does access to financial markets could promote development in African countries? Find out how different financial innovations have been introduced and whether they have successfully promoted entrepreneurship and productivity. Use a case-study setting.

- Can the private sector be a motor for development? Choose a country and examine the structure of its private sector (informal economy, tax structure). 

- How is COVID going to impact the development of low-income countries? Pick two African countries. Compare and contrast how COVID has impacted them, what measures have been taken to respond, and what policies are being implemented to limit the economic effects.
